#!/usr/bin/env bash
# Xray-OneClick global constants and default configuration paths.

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
PLAIN="\033[0m"

SERVICE_NAME="xray"
CONFIG_DIR="/etc/xray"
CONFIG_FILE="${CONFIG_DIR}/config.json"
STATE_FILE="${CONFIG_DIR}/installer-state.json"
ASSET_DIR="/usr/local/share/xray"
BIN_PATH="${XRAY_BIN:-/usr/local/bin/xray}"
SHORTCUT_PATH="/usr/local/bin/ike"
LEGACY_SHORTCUT_PATH="/usr/local/bin/sb"
INSTALLER_DIR="/usr/local/share/ike"
INSTALLER_PATH="${INSTALLER_DIR}/install.sh"
SCRIPT_NAME="Xray-OneClick"
SCRIPT_VERSION="1.1.11"
REPO_URL="https://github.com/ike-sh/Xray-OneClick"
RAW_SCRIPT_URL="https://raw.githubusercontent.com/ike-sh/Xray-OneClick/main/install.sh"
XRAY_RELEASE_API_STABLE="https://api.github.com/repos/XTLS/Xray-core/releases/latest"
XRAY_RELEASE_API_PRERELEASE="https://api.github.com/repos/XTLS/Xray-core/releases?per_page=20"
XRAY_RELEASE_API_TAG_BASE="https://api.github.com/repos/XTLS/Xray-core/releases/tags"
MIN_ROOT_FREE_KB="204800"

SS_TAG="ss2022-in"
VLESS_TAG="vless-enc-in"
REALITY_TAG="vless+tcp+reality"
REALITY_DEFENDER_TAG="reality-defender"
REALITY_STATE_KEY="vless_reality"
REALITY_PORT_MIN="20000"
REALITY_PORT_MAX="50000"
REALITY_DEFENDER_PORT_MIN="39000"
REALITY_DEFENDER_PORT_MAX="49999"
REALITY_FLOW_DEFAULT="xtls-rprx-vision"
REALITY_FLOW_NONE="none"
VLESS_XHTTP_FM_TAG="vless-enc-xhttp-finalmask-in"
VLESS_XHTTP_FM_STATE_KEY="vless_xhttp_finalmask"
VLESS_XHTTP_REALITY_TAG="vless+xhttp+reality"
VLESS_XHTTP_REALITY_STATE_KEY="vless_xhttp_reality"
VLESS_ENC_REALITY_TAG="vless+enc+reality"
VLESS_ENC_REALITY_STATE_KEY="vless_enc_reality"
VLESS_FULLSTACK_TAG="vless+enc+xhttp+reality+finalmask"
VLESS_FULLSTACK_STATE_KEY="vless_fullstack"
SOCKS_TAG="socks-in"
TUNNEL_TAG_PREFIX="tunnel-"
LEGACY_FORWARD_TAG_PREFIX="forward-"
FORWARD_TAG_PREFIX="$TUNNEL_TAG_PREFIX"
TUNNEL_PROTOCOL="${TUNNEL_PROTOCOL:-dokodemo-door}"
BLOCK_OUTBOUND_TAG="BLOCK"
DEFAULT_SAFETY_BLOCK_PORTS="25,135,137,138,139,445,465,587"
ENHANCED_SAFETY_BLOCK_PORTS="69,161,162,389,636,1900,5353,5355,11211"

LINK_VIEW_MODE="dual"
OS_TYPE=""
INIT_SYSTEM=""
ARCH=""
XRAY_ASSET=""

REALITY_SNI_CANDIDATES=(
    "www.abmindustriesgroup.com"
    "www.microsoft.com"
    "www.oracle.com"
    "www.ibm.com"
    "www.amazon.com"
    "www.samsung.com"
    "www.nvidia.com"
)
